name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@HEAD

      - name: Check type
        run: yarn type-check

      - name: Check lint
        run: yarn lint

      - name: Check style
        run: yarn format

      - name: Check commits messages
        uses: wagoid/commitlint-github-action@v4

      - name: Integration tests
        run: yarn cy:run

      - name: Build
        run: yarn build

      - name: Realese
        uses: cycjimmy/semantic-release-action@v3
